---
title: "Sweetpotato Storage Root Growth Prediction"
output: html_document
params:
  summary_tbl: NA
  climate_summary_tbl: NA
  soil_profile_tbl: NA
  soil_agg_tbl: NA
  plain_language_html: NA
  equation: NA
  pred_plot: NA
  pred_tbl: NA
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

## Run summary

```{r}
knitr::kable(params$summary_tbl)
```

## What this means

```{r results='asis'}
cat(params$plain_language_html)
```

## Climate & water balance

```{r}
knitr::kable(params$climate_summary_tbl)
```

## Soil profile used

```{r}
knitr::kable(params$soil_profile_tbl)
```

```{r}
knitr::kable(params$soil_agg_tbl)
```

## Prediction

**Equation:** `r params$equation`

```{r fig.width=8, fig.height=4}
print(params$pred_plot)
```

```{r}
knitr::kable(params$pred_tbl)
```

---
*Generated by the Sweetpotato Biomass Prediction Tool. Reference: Mariella Carbajal et al. (2026),
Modeling Sweetpotato Storage Root Growth Using Piecewise Linear and Logistic Functions Under
Variable Water Conditions.*
